"""Small, QCoDeS-free ATS9371 acquisition package."""

from .ats9371 import (
    AcquisitionConfig,
    BoardInfo,
    CaptureSession,
    DmaBuffer,
    TriggerConfig,
    abort_capture,
    adc_codes_to_volts,
    analyze_tone,
    arm_capture,
    configure_ats9371,
    configure_channel,
    free_capture,
    get_board_info,
    open_ats9371,
    start_capture,
    wait_for_capture,
)
from .ats_api import ATSApi, AlazarError
from .demodulation import (
    average_shots,
    correct_interleaving_offsets,
    digital_downconvert,
    dispersive_demodulate,
    dispersive_demodulate_seconds,
    emission_demodulate,
    integrate_iq_window,
    moving_average_iq,
    moving_average_time_axis,
    phase_align_iq,
    recover_coherent_envelope,
    recover_clock_referenced_envelope,
    seconds_to_samples,
    subtract_baseline,
)

__all__ = [
    "ATSApi",
    "AcquisitionConfig",
    "AlazarError",
    "BoardInfo",
    "CaptureSession",
    "DmaBuffer",
    "TriggerConfig",
    "abort_capture",
    "adc_codes_to_volts",
    "analyze_tone",
    "average_shots",
    "correct_interleaving_offsets",
    "arm_capture",
    "configure_ats9371",
    "configure_channel",
    "digital_downconvert",
    "dispersive_demodulate",
    "dispersive_demodulate_seconds",
    "emission_demodulate",
    "free_capture",
    "get_board_info",
    "integrate_iq_window",
    "moving_average_iq",
    "moving_average_time_axis",
    "phase_align_iq",
    "recover_coherent_envelope",
    "recover_clock_referenced_envelope",
    "open_ats9371",
    "seconds_to_samples",
    "start_capture",
    "subtract_baseline",
    "wait_for_capture",
]
